### PR TITLE
convert 1D shape into largest perfect md shape possible

### PR DESCRIPTION
**Pull request by Christian-B**
Simplest version uses a m D shape with all sides the same size.

So 256 in 3D would be (6,6,6) where a shape of (7,6,6) would be possible

### CODE REVIEW

**Review by andrewgait — APPROVED** [review]
No objections as long as it doesn't break any current tests.

**Comment by andrewgait** [comment]
Though perhaps a test could also be added using the script at http://spinnakermanchester.github.io/development/2d_convolutions.html

**Comment by Christian-B** [comment]
This is only one of several options.

Another is to keep as master and require the setting of max atoms.

Another is to have 2D defaults

**Comment by andrewgait** [comment]
I don't know how this was resolved so leaving it open and re-assigning it.

**Comment by Christian-B** [comment]
Assume this is no longer needed.

**Comment by rowleya** [comment]
Yes, I think this was a test on the path, but is now no longer needed.

**Pull request closed without merging**
