### PR TITLE
connective based placer is dead and needs a burial

### PR DESCRIPTION
**Pull request by Christian-B**
resolves https://github.com/SpiNNakerManchester/PACMAN/issues/248

### CODE REVIEW

**Comment by alan-stokes** [comment]
why was this nuked?! the heuristic in here was good. im saying its the best out there, and it may be obsoleted with the spreader placer. but still...... if your going to nuke old placers. there's a good few others we don't use anymore......

**Comment by Christian-B** [comment]
Feel free to bring it back AND fix it.

**Comment by alan-stokes** [comment]
added to my pile.

**Comment by Christian-B** [comment]
good luck

**Pull request merged**
