### PR TITLE
fixes chimps lazyness

### PR DESCRIPTION
**Pull request by alan-stokes**

### CODE REVIEW

**Comment by rowleya** [comment]
> I disagree!
> 
> From within the same class I think it is perfectly acceptible to access parameters directly!

This is correct, though note that if you made the variables double-underscore, I don't think you can (i.e. private variables don't work the same as they do in Java).  If we aren't going to do this, they can be left as they are.  As a side note, the "else" should then probably be "else if isinstance(other, VariableSDRAM) to protect the access from other rubbish, but then equally we don't do this sort of check anywhere else i.e. the assumption is that the input here is an SDRAM object.

**Comment by alan-stokes** [comment]
well if your going to reject my fix. then you might as well delete the brnach as well

**Comment by Christian-B** [comment]
I was being polite and leaving the branch for you to argue your case.

Now that I have won the branch has been deleted.

**Comment by alan-stokes** [comment]
think you win only coz the energy levels have dropped below the effort to reach my cliff. lol

**Pull request closed without merging**
