### PR TITLE
Sorted zoned

### PR DESCRIPTION
**Pull request by Christian-B**
Zonded infio allocator version 2.

Handles machine vertexes partitions with multiple partitions.
Note: ApplicationRoutingInfos is not yet used by any other algorithms so left for farther development 

Handles FixedKeyAndMaskConstraint. Even ones with a VERY big number of neurons/keys needed

If multiple application vertexes have exactly the same set of target cores they will be infos

### CODE REVIEW

**Comment by alan-stokes** [comment]
conflicts

**Comment by Christian-B** [comment]
Too far behind and too messy to merge!

**Comment by alan-stokes** [comment]
deleting branch or not?

**Comment by Christian-B** [comment]
branch left of history

**Pull request closed without merging**
